name: ui-kit-ts - default

on:
    push:
        branches:
            - "main"
    release:
        types: [created]
    schedule:
        - cron: "0 6 * * 1" # At 06:00 on Monday
    workflow_dispatch: # to run from the Actions tab on GitHub

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [24]
            pnpm-version: [10]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 #checkout full history so we can get the latest tag

            - uses: pnpm/action-setup@v4
              with:
                version: "${{ matrix.pnpm-version }}"

            - uses: actions/setup-node@v4
              with:
                node-version: "${{ matrix.node-version }}"
                cache: "pnpm"

              # if i run the deployment of the github pages from the github web ui, without a release, then there is no github.event.release...
            - name: get latest tag
              id: get_latest_tag
              run: |
                  LATEST_TAG=$(git tag --sort=-version:refname | head -n 1)
                  echo latest_tag=${LATEST_TAG} >> $GITHUB_OUTPUT

            - name: Install
              run: pnpm install

            - name: Build Library
              run: pnpm run build:lib

            - name: Build Showcase
              run: VITE_GH_RELEASE_TAG=${{ steps.get_latest_tag.outputs.latest_tag }} pnpm run build:sc

            - name: Deploy Showcase to Github Pages
              # run deploy either on release or ...
              if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'release')  }}
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: docs
                  folder: dist-showcase
                  single-commit: true

    publish:
        needs: build
        if: ${{ github.event_name == 'release' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - uses: pnpm/action-setup@v4
              with:
                version: "${{ matrix.pnpm-version }}"
            
            - uses: actions/setup-node@v4
              with:
                node-version: "${{ matrix.node-version }}"
                cache: "pnpm"

            - name: Get release version
              id: release
              run: |
                  FULL_VERSION=${{ github.event.release.tag_name }}
                  SHORT_VERSION=${FULL_VERSION:1}
                  echo short_version=${SHORT_VERSION} >> $GITHUB_OUTPUT

            - name: Configure Git user
              run: |
                  git config user.email "actions@github.com"
                  git config user.name "GitHub Actions"

            - name: Update release version
              run: pnpm version --no-git-tag-version ${{ steps.release.outputs.short_version }}

            - name: Install Dependencies
              run: pnpm install

            - name: Build Release
              run: pnpm run build:lib

            - name: Publish to npmjs
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
