name: ui-kit-ts

on:
  push:
    branches:
      - "main"

jobs:
  build-library:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'library'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: npm ci
      - run: npm run build
#
#  build-library:
#    needs: install-and-test
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: 'library'
#    name: "Bump version and create changelog with commitizen"
#    steps:
#      - name: Check out
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#          token: "${{ secrets.GITHUB_TOKEN }}"
#      - id: cz
#        name: Bump package
#        uses: commitizen-tools/commitizen-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Print Version
#        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
#      - name: Build library
#        run: npm ci build

#  publish-gpr:
#    needs: tag-and-bump
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: 'library'
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '19.x'
#          registry-url: 'https://registry.npmjs.org'
#
#      - name: Publish to npmjs
#        run: npm publish --access public
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
  deploy-showcase:
    needs: build-library
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'showcase'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Install showcase
        run: npm ci

      - name: Build showcase
        run: npm run build

      - name: Deploy Showcase to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: docs
          folder: build
          single-commit: true
