name: Release

on:
  workflow_run:
    workflows: [ "Build bump tag" ]
    types:
      - completed
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_PUBLISH_TOKEN}}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public
