name: Release

on:
  workflow_run:
    workflows: [ "Build bump tag" ]
    types:
      - completed
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npmjs
        run: npm --prefix library publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

      - name: Build showcase
        run: npm --prefix showcase ci build

      - name: Deploy Showcase to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: docs
          folder: showcase/build
          single-commit: true
