name: ui-kit-ts

on:
  push:
    branches:
      - "main"
  release:
    types: [ created ]
  schedule:
    - cron: '0 6 * * 1' # At 06:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.1.0'
          npm-version: '9.4.2'
      - name: npm install library
        working-directory: ./library
        run: npm install

      - name: npm build library
        working-directory: ./library
        run: npm run build

      - name: npm install showcase
        working-directory: ./showcase
        run: npm install

      - name: npm build showcase
        working-directory: ./showcase
        run: npm run build

      - name: deploy Showcase to Github Pages
        if: ${{ github.event_name == 'release' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: docs
          folder: showcase/build
          single-commit: true

  publish:
    needs: build
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'library'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.1.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Get release version
        id: release
        run: |
          FULL_VERSION=${{ github.event.release.tag_name }}
          SHORT_VERSION=${FULL_VERSION:1}
          echo shortVersion=${SHORT_VERSION} >> $GITHUB_OUTPUT

      - name: Update release version
        working-directory: ./library
        run: npm version ${{ steps.release.outputs.shortVersion }}

      - name: Publish to npmjs
        working-directory: ./library
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
